version: '3'
services:
  minecraft:
    build: ./docker
    ports:
     - "25565:25565"
     - "25575:25575"
    volumes:
     - server_data:/server
    container_name: minecraft
volumes:
  server_data:
