version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/docker-image-cache.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docker-image-cache.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=minecraft-forge -t minecraft-forge .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/docker-image-cache.tar minecraft-forge
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/docker-image-cache.tar
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      # - restore_cache:
      #     keys:
      #       - v1-{{ .Branch }}
      #     paths:
      #       - /caches/docker-image-cache.tar
      - run:
          name: "Tag and Push Docker image to Docker Hub"
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker tag minecraft-forge bckr/minecraft-forge:$CIRCLE_TAG
            docker push bckr/minecraft-forge:$CIRCLE_TAG
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9]\+\.[0-9]\+\.[0-9]\+$/
            branches:
              ignore: /.*/
